### ISSUE TITLE
Encrypting Network Comminucation to AD

### ISSUE THREAD

**Issue by koalup** [auth0/passport-windowsauth#22]
This module works really well, but I was curious if it were possible to encrypt network communication from the node server to active directory. I'm using non-integrated authentication and didn't see an option in the readme for configuring passport-windowsauth to talk to AD over ssl.

Thanks!

**Comment by koalup** [comment]
Hey, I just wanted to follow up regarding this issue. I created a pull request with the changes and was wondering if there's anything else that I need to do to get this change into the main branch. 

Thanks!

**Comment by futurechan** [comment]
:+1:
